#my.datasource.url=local.db.com
#my.datasource.username=local_user
#my.datasource.password=password
#my.datasource.etc.max-connection=1
#my.datasource.etc.timeout=3500ms
#my.datasource.etc.options=CACHE, ADMIN

my:
  datasource:
    url: local.db.com
    username: local_user
    password: password
    etc:
      max-connection: 1
      timeout: 3500ms
      options: CACHE, ADMIN
---
spring:
  config:
    activate:
      on-profile: dev
my:
  datasource:
    url: dev.db.com
    username: dev_user
    password: password
    etc:
      max-connection: 10
      timeout: 3500ms
      options: CACHE, ADMIN
---
spring:
  config:
    activate:
      on-profile: prod
my:
  datasource:
    url: prod.db.com
    username: prod_user
    password: password
    etc:
      max-connection: 50
      timeout: 10s
      options: CACHE, ADMIN